-- Description: This file contains the SQL code to create the data wrangling procedures.
-- Creación del procedimiento para la carga de datos de la tabla de hechos FC_VENTA_VS_MANTENIMIENTO


CREATE OR REPLACE PROCEDURE `CRG_FC_VENTA_VS_MANTENIMIENTO`(VAR_SCHEMA varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_EMPRESA varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_FECHA_INICIO date NULL, VAR_FECHA_FIN date NULL, VAR_LINEA_NEGOCIO_NUEVOS varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_LINEA_NEGOCIO_EXONERADOS varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, VAR_LINEA_NEGOCIO_MNT varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL) RETURNS void AS
/***********************************************************************************************************************
  * Descripcion: Cargar Datos FC_VENTAS_NUEVOS_EXONERADOS_MANTENIMIENTO
  * Version: 1.0.0
  * Fecha Creacion: 29/05/2023
  * Autor: Byron Vinueza 
  * Comentario : Para Ejecutar = CALL FC_VENTA_VS_MANTENIMIENTO(DSA,'01', FECHA_INICIA, FECHA_FIN,LINEA_NEGOCIO_1,LINEA_NEGOCIO_2 )
  -------------------------------------------------------------------------
  * Fecha Modificacion: 13/09/2024
  * Modificado: IS Cambios y aumento de campos
*************************************************************************************************************************/
DECLARE
	VAR_SQL VARCHAR(8000);
	VAR_ERROR VARCHAR(4000);
	VAR_DT_INICIO TIMESTAMP = CURRENT_TIMESTAMP;
BEGIN
START TRANSACTION;
	INSERT INTO CTR.LOG_PROCESO (MODULO, ETAPA,DT_FECHA_INICIO) VALUES ('TABLA DE HECHOS',CONCAT('INICIO ',VAR_SCHEMA,'.CRG_FC_VENTA_VS_MANTENIMIENTO'),VAR_DT_INICIO);
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP_VENTAS_NUEVOS_EXONERADOS');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP_VENTA_MANTENIMIENTO');
	 EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	/*Descripción: Creación de la tabla temporal de las ventas efectivas en las líneas de negocios nuevos y exonerados exluyendo a los clientes 
	 * 	CARLOS LARREA Y COMERCIAL HIDROVO*/
	
	VAR_SQL=CONCAT(' CREATE TABLE DSA.TMP_VENTAS_NUEVOS_EXONERADOS (KEY (NO_FACTU,CHASIS) USING CLUSTERED COLUMNSTORE)
									SELECT
											AA.FECHA , AA.NO_FACTU , AA.NO_FISICO , AA.TIPO_DOC , AA.NO_VENDEDOR
											, BB.CHASIS
											, AA.LINEA , AA.NO_PEDIDO
											, NVL(AA.CENTRO_ORIGEN,AA.CENTROD) COD_AGENCIA
											, AA.CENTROD COD_AGENCIA_FACTURA
											, AA.NO_CIA COD_EMPRESA
											, AA.LINEA_NEGOCIO
											, AA.FECHA_SALIDA
											, CASE WHEN (AA.LINEA IN ("CY", "C8", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C9", "D1")) THEN "TSN"
														WHEN ((I.SALDO_FINANCIAR = 0) AND (I.CUOTA_DE_ALCANCE = 0)) THEN "CON"
														WHEN ((I.SALDO_FINANCIAR > 0) AND (AA.LINEA  = "CB")) THEN "CD"
														WHEN ((I.SALDO_FINANCIAR = 0) AND (I.CUOTA_DE_ALCANCE > 0) AND (AA.LINEA  = "CB")) THEN "CA"
														WHEN (AA.LINEA  = "SV") THEN "CA"
														WHEN (((I.CUOTA_DE_ALCANCE > 0) OR (I.SALDO_FINANCIAR= 0)) AND (AA.LINEA  <> "CB")) THEN "CT"
														WHEN (AA.LINEA  = "VE") THEN "CD"
											ELSE "CT" END AS COD_FINANCIACION
									FROM  
											',VAR_SCHEMA,'.S3S_FAC_VENTAS_CAB AA
											INNER JOIN ',VAR_SCHEMA,'.S3S_FAC_VENTAS_VEHICULOS BB ON AA.NO_CIA =BB.NO_CIA AND AA.RUTA =BB.RUTA AND AA.TIPO_DOC =BB.TIPO_DOC AND AA.NO_FACTU =BB.NO_FACTU
											INNER JOIN ',VAR_SCHEMA,'.S3S_SVFCOTI I ON  AA.CENTROD = I.CENTRO AND AA.NO_PEDIDO = I.NUMERO_COTIZACION AND I.SVLICODI = AA.LINEA_NEGOCIO  AND AA.NO_CIA = I.NO_CIA
									WHERE 
											AA.NO_CIA = "',VAR_EMPRESA,'"
											AND AA.LINEA_NEGOCIO = "',VAR_LINEA_NEGOCIO_NUEVOS,'"
											AND NVL(AA.IND_ANU_DEV,"X")<>"A"
											AND DATE(AA.FECHA) BETWEEN "',VAR_FECHA_INICIO,'" AND "',VAR_FECHA_FIN,'"  
											AND AA.NO_CLIENTE NOT IN (69157,186117,20781,23437,63323)
								');
	EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

	VAR_SQL=CONCAT('INSERT INTO ',VAR_SCHEMA,'.TMP_VENTAS_NUEVOS_EXONERADOS
									SELECT
											AA.FECHA
											, AA.NO_FACTU
											, AA.NO_FISICO
											, AA.TIPO_DOC , AA.NO_VENDEDOR
											, BB.CHASIS
											, AA.LINEA , AA.NO_PEDIDO
											, NVL(AA.CENTRO_ORIGEN,AA.CENTROD) COD_AGENCIA
											, AA.CENTROD COD_AGENCIA_FACTURA
											, AA.NO_CIA COD_EMPRESA
											, AA.LINEA_NEGOCIO
											, AA.FECHA_SALIDA
											, CASE WHEN (AA.LINEA IN ("CY", "C8", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C9", "D1")) THEN "TSN"
														WHEN ((I.SALDO_FINANCIAR = 0) AND (I.CUOTA_DE_ALCANCE = 0)) THEN "CON"
														WHEN ((I.SALDO_FINANCIAR > 0) AND (AA.LINEA  = "CB")) THEN "CD"
														WHEN ((I.SALDO_FINANCIAR = 0) AND (I.CUOTA_DE_ALCANCE > 0) AND (AA.LINEA  = "CB")) THEN "CA"
														WHEN (AA.LINEA  = "SV") THEN "CA"
														WHEN (((I.CUOTA_DE_ALCANCE > 0) OR (I.SALDO_FINANCIAR= 0)) AND (AA.LINEA  <> "CB")) THEN "CT"
														WHEN (AA.LINEA  = "VE") THEN "CD"
												ELSE "CT" END AS COD_FINANCIACION
									FROM 
											',VAR_SCHEMA,'.S3S_FAC_VENTAS_CAB AA
											INNER JOIN ',VAR_SCHEMA,'.S3S_FAC_VENTAS_VEHICULOS BB ON AA.NO_CIA =BB.NO_CIA AND BB.RUTA =AA.RUTA AND BB.TIPO_DOC =AA.TIPO_DOC AND BB.NO_FACTU =AA.NO_FACTU
											INNER JOIN ',VAR_SCHEMA,'.S3S_SVFCOTI I ON  AA.CENTROD = I.CENTRO AND AA.NO_PEDIDO = I.NUMERO_COTIZACION AND I.SVLICODI = AA.LINEA_NEGOCIO  AND AA.NO_CIA = I.NO_CIA
									WHERE 
											AA.NO_CIA = "',VAR_EMPRESA,'"
											AND AA.LINEA_NEGOCIO = "',VAR_LINEA_NEGOCIO_EXONERADOS,'"
											AND NVL(AA.IND_ANU_DEV,"X")<> "A"
											AND AA.TIPO_DOC  IN ("EX","NE")
											AND DATE(AA.FECHA) BETWEEN "',VAR_FECHA_INICIO,'"   AND "',VAR_FECHA_FIN,'" 
											AND AA.NO_CLIENTE NOT IN (69157,186117,20781,23437,63323) 
									');
	EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;

-- Descripción: Creación de la tabla temporal de las ordenes creadas de los vehículos que ingresan al taller a mantenimiento de los  1000, 5000, 10000 km 
	
	VAR_SQL=CONCAT('CREATE TABLE ',VAR_SCHEMA,'.TMP_VENTA_MANTENIMIENTO (KEY (CHASIS) USING CLUSTERED COLUMNSTORE)
									SELECT 
											T.*
											, T1.CODIGO AS AGENCIA_1 
											, T1.COD_TECNICO_ASESOR AS COD_TECNICO_ASESOR1
											, T1.KM_RELACIONADO AS K1
											, T1.FECHA_FACTURA FECHA_FACTURA_K1
											, T2.CODIGO AS AGENCIA_5
											, T2.COD_TECNICO_ASESOR AS COD_TECNICO_ASESOR5
											, T2.KM_RELACIONADO AS K5
											, T2.FECHA_FACTURA FECHA_FACTURA_K5
											, T3.CODIGO AS AGENCIA_10
											, T3.COD_TECNICO_ASESOR AS COD_TECNICO_ASESOR10
											, T3.KM_RELACIONADO AS K10
											, T3.FECHA_FACTURA FECHA_FACTURA_K10
									FROM 
											',VAR_SCHEMA,'.TMP_VENTAS_NUEVOS_EXONERADOS  T
											LEFT JOIN (
																	SELECT
																			B.CHASIS_NO  , A.KILOMETRAJE, A.CODIGO
																			, A.TECNIASESOR_ID COD_TECNICO_ASESOR
																			, (D.KM_RELACIONADO) KM_RELACIONADO
																			, A.FECHA_CIERRE FECHA_FACTURA
																	FROM 
																			',VAR_SCHEMA,'.S3S_SE_ORDENREP A
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_VEHICULOS B ON A.NO_CIA = B.NO_CIA AND  A.NUMCBS = B.NUMCBS
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_TRABORDEN C ON A.NO_CIA = C.NO_CIA AND A.CODIGO = C.CODIGO AND A.ORDENREP_ID = C.ORDENREP_ID
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_MENUSERV3 D ON C.NO_CIA = D.NO_CIA AND C.CODSERV1 = D.CODSERV1 AND C.CODSERV2 = D.CODSERV2 AND C.CODSERV3 = D.CODSERV3
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_ORDENREP_NC NC ON NC.NO_CIA = A.NO_CIA AND A.ORDENREP_ID = NC.ORDENREP_ID_ORIGEN
																	WHERE 
																			A.NO_CIA = "',VAR_EMPRESA,'"
																			AND A.LINEA_NEGOCIO = "',VAR_LINEA_NEGOCIO_MNT,'"
																			AND A.ESTADO_ID in ("85","90")
																			AND D.KM_RELACIONADO = 1000
																			AND NC.ORDENREP_ID_ORIGEN IS NULL
																) T1  ON T1.CHASIS_NO = T.CHASIS AND YEAR(T1.FECHA_FACTURA) >= YEAR(T.FECHA)
											LEFT JOIN (
																	SELECT
																			B.CHASIS_NO , A.KILOMETRAJE, A.CODIGO
																			, A.TECNIASESOR_ID COD_TECNICO_ASESOR
																			, NVL(A.FECHA_FACTURA,A.FECHA_CIERRE) FECHA_FACTURA
																			, (D.KM_RELACIONADO) KM_RELACIONADO
																	FROM 
																			',VAR_SCHEMA,'.S3S_SE_ORDENREP A
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_VEHICULOS B ON A.NO_CIA = B.NO_CIA AND  A.NUMCBS = B.NUMCBS
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_TRABORDEN C ON A.NO_CIA = C.NO_CIA AND A.CODIGO = C.CODIGO AND A.ORDENREP_ID = C.ORDENREP_ID
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_MENUSERV3 D ON C.NO_CIA = D.NO_CIA AND C.CODSERV1 = D.CODSERV1 AND C.CODSERV2 = D.CODSERV2 AND C.CODSERV3 = D.CODSERV3
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_ORDENREP_NC NC ON NC.NO_CIA = A.NO_CIA AND A.ORDENREP_ID = NC.ORDENREP_ID_ORIGEN
																	WHERE 
																			A.NO_CIA = "',VAR_EMPRESA,'"
																			AND A.LINEA_NEGOCIO = "',VAR_LINEA_NEGOCIO_MNT,'"
																			AND A.ESTADO_ID in ("85","90")
																			AND D.KM_RELACIONADO = 5000
																			AND NC.ORDENREP_ID_ORIGEN IS NULL
																) T2  ON T2.CHASIS_NO = T.CHASIS
											LEFT JOIN (
																	SELECT
																			B.CHASIS_NO , A.KILOMETRAJE, A.CODIGO   
																			, A.TECNIASESOR_ID COD_TECNICO_ASESOR
																			, NVL(A.FECHA_FACTURA,A.FECHA_CIERRE) FECHA_FACTURA
																			, (D.KM_RELACIONADO) KM_RELACIONADO
																	FROM 
																			',VAR_SCHEMA,'.S3S_SE_ORDENREP A
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_VEHICULOS B ON A.NO_CIA = B.NO_CIA AND  A.NUMCBS = B.NUMCBS
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_TRABORDEN C ON A.NO_CIA = C.NO_CIA AND A.CODIGO = C.CODIGO AND A.ORDENREP_ID = C.ORDENREP_ID
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_MENUSERV3 D ON C.NO_CIA = D.NO_CIA AND C.CODSERV1 = D.CODSERV1 AND C.CODSERV2 = D.CODSERV2 AND C.CODSERV3 = D.CODSERV3
																			LEFT JOIN ',VAR_SCHEMA,'.S3S_SE_ORDENREP_NC NC ON NC.NO_CIA = A.NO_CIA AND A.ORDENREP_ID = NC.ORDENREP_ID_ORIGEN
																	WHERE 
																			A.NO_CIA = "',VAR_EMPRESA,'"
																			AND A.LINEA_NEGOCIO = "',VAR_LINEA_NEGOCIO_MNT,'"
																			AND A.ESTADO_ID in ("85","90")
																			AND D.KM_RELACIONADO = 10000
																			AND NC.ORDENREP_ID_ORIGEN IS NULL
																) T3  ON T3.CHASIS_NO = T.CHASIS 
									');
	EXECUTE IMMEDIATE VAR_SQL;
	COMMIT;	

	VAR_SQL=CONCAT('DELETE FROM DWH.FC_VENTA_VS_MANTENIMIENTO A 
									WHERE A.SK_EMPRESA = (SELECT SK_EMPRESA FROM DWH.DIM_EMPRESA WHERE COD_EMPRESA = "',VAR_EMPRESA,'")
									AND SK_FECHA >= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_INICIO,'") 
									AND SK_FECHA <= (SELECT SK_FECHA FROM DWH.DIM_FECHA WHERE FECHA = "',VAR_FECHA_FIN,'") 
									');
	EXECUTE IMMEDIATE VAR_SQL;			
	COMMIT;
	
/*Descripción: Inserción de registros en la tabla de hechos */

	VAR_SQL=CONCAT('INSERT INTO DWH.FC_VENTA_VS_MANTENIMIENTO 
									SELECT 
											EM.SK_EMPRESA
											, NVL(FF.SK_FECHA,19700101) SK_FECHA
											, AA.NO_FACTU
											, AA.NO_FISICO
											, TD.SK_TIPO_DOCUMENTO
											, DV.SK_VENDEDOR 
											, TF.SK_TIPO_FINANCIACION 
											, NVL(AG1.SK_AGENCIA,1) SK_AGENCIA
											, NVL(AG2.SK_AGENCIA,1) SK_AGENCIA_FACTURA
											, NVL(LI.SK_LINEA_NEGOCIO,1) SK_LINEA_NEGOCIO
											, NVL(FF3.SK_FECHA ,19700101) SK_FECHA_SALIDA
											, NVL(VEH.SK_VEHICULO,1) SK_VEHICULO
											, NVL(A1.SK_AGENCIA,1) SK_AGENCIA_MNT1
											, NVL(TA1.SK_TECNICO_ASESOR,1) SK_TECNICO_ASESOR1
											, NVL(AA.K1,-1) AS MANTENIMIENTO_1000
											, NVL(FK1.SK_FECHA,19700101) AS SK_FECHA_MANTENIMIENTO_1000
											, NVL(A5.SK_AGENCIA,1) SK_AGENCIA_MNT5
											, NVL(TA5.SK_TECNICO_ASESOR,1) SK_TECNICO_ASESOR5
											, NVL(AA.K5,-1) AS MANTENIMIENTO_5000
											, NVL(FK5.SK_FECHA,19700101)  AS SK_FECHA_MANTENIMIENTO_5000
											, NVL(A10.SK_AGENCIA,1) SK_AGENCIA_MNT10
											, NVL(TA10.SK_TECNICO_ASESOR,1) SK_TECNICO_ASESOR10
											, NVL(AA.K10,-1) AS MANTENIMIENTO_10000
											, NVL(FK10.SK_FECHA,19700101)  AS SK_FECHA_MANTENIMIENTO_10000
											, NVL(FV.SK_FINANCIACION,1 ) SK_FINANCIACION
									FROM 
											DSA.TMP_VENTA_MANTENIMIENTO AA
											LEFT JOIN DWH.DIM_EMPRESA EM ON EM.COD_EMPRESA=AA.COD_EMPRESA
											LEFT JOIN DWH.DIM_FECHA FF ON DATE(FF.FECHA)=DATE(AA.FECHA)
											LEFT JOIN DWH.DIM_TIPO_DOCUMENTO TD ON TD.COD_TIPO_DOCUMENTO=AA.TIPO_DOC AND  TD.COD_EMPRESA =AA.COD_EMPRESA
											LEFT JOIN DWH.DIM_VENDEDOR DV ON DV.COD_VENDEDOR =AA.NO_VENDEDOR AND DV.COD_EMPRESA=AA.COD_EMPRESA
											LEFT JOIN DWH.DIM_TIPO_FINANCIACION TF  ON TF.COD_TIPO_FINANCIACION =AA.LINEA AND TF.COD_EMPRESA =AA.COD_EMPRESA
											LEFT JOIN DWH.DIM_FINANCIACION_VH FV ON FV.COD_FINANCIACION = AA.COD_FINANCIACION
											LEFT JOIN DWH.DIM_AGENCIA AG1 ON AG1.COD_EMPRESA =AA.COD_EMPRESA AND AG1.COD_AGENCIA =AA.COD_AGENCIA
											LEFT JOIN DWH.DIM_AGENCIA AG2 ON AG2.COD_EMPRESA =AA.COD_EMPRESA AND AG2.COD_AGENCIA =AA.COD_AGENCIA_FACTURA
											LEFT JOIN DWH.DIM_LINEA_NEGOCIO LI ON LI.COD_EMPRESA =AA.COD_EMPRESA AND LI.COD_LINEA_NEGOCIO =AA.LINEA_NEGOCIO 
											LEFT JOIN DWH.DIM_FECHA FF3 ON  DATE(FF3.FECHA) = DATE(AA.FECHA_SALIDA)
											LEFT JOIN DWH.DIM_VEHICULO VEH ON VEH.CHASIS=AA.CHASIS AND VEH.COD_EMPRESA = AA.COD_EMPRESA AND VEH.COD_LINEA_NEGOCIO =AA.LINEA_NEGOCIO
											LEFT JOIN DWH.DIM_FECHA FK1 ON DATE(FK1.FECHA) = DATE(AA.FECHA_FACTURA_K1) 
											LEFT JOIN DWH.DIM_FECHA FK5 ON DATE(FK5.FECHA) = DATE(AA.FECHA_FACTURA_K5) 
											LEFT JOIN DWH.DIM_FECHA FK10 ON DATE(FK10.FECHA) = DATE(AA.FECHA_FACTURA_K10) 
											LEFT JOIN DWH.DIM_AGENCIA A1 ON AA.COD_EMPRESA = A1.COD_EMPRESA AND AA.AGENCIA_1 = A1.COD_AGENCIA 
											LEFT JOIN DWH.DIM_AGENCIA A5 ON AA.COD_EMPRESA = A5.COD_EMPRESA AND AA.AGENCIA_5 = A5.COD_AGENCIA 
											LEFT JOIN DWH.DIM_AGENCIA A10 ON AA.COD_EMPRESA = A10.COD_EMPRESA AND AA.AGENCIA_10 = A10.COD_AGENCIA 
											LEFT JOIN DWH.DIM_TECNICO_ASESOR TA1 ON AA.COD_EMPRESA = TA1.COD_EMPRESA AND AA.COD_TECNICO_ASESOR1 = TA1.COD_TECNICO_ASESOR 
											LEFT JOIN DWH.DIM_TECNICO_ASESOR TA5 ON AA.COD_EMPRESA = TA5.COD_EMPRESA AND AA.COD_TECNICO_ASESOR5 = TA5.COD_TECNICO_ASESOR 
											LEFT JOIN DWH.DIM_TECNICO_ASESOR TA10 ON AA.COD_EMPRESA = TA10.COD_EMPRESA AND AA.COD_TECNICO_ASESOR10 = TA10.COD_TECNICO_ASESOR 
								');
				EXECUTE IMMEDIATE VAR_SQL;
				COMMIT;	
			
			VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP_VENTAS_NUEVOS_EXONERADOS');
				 EXECUTE IMMEDIATE VAR_SQL;
				COMMIT;

			VAR_SQL=CONCAT('DROP TABLE IF EXISTS ',VAR_SCHEMA,'.TMP_VENTA_MANTENIMIENTO');
				 EXECUTE IMMEDIATE VAR_SQL;
				COMMIT;
						
END;
